export default {
	'baidu-map': [
		'click',
		'dblclick',
		'rightclick',
		'rightdblclick',
		'maptypechange',
		'mousemove',
		'mouseover',
		'mouseout',
		'movestart',
		'moving',
		'moveend',
		'zoomstart',
		'zoomend',
		'addoverlay',
		'addcontrol',
		'removecontrol',
		'removeoverlay',
		'clearoverlays',
		'dragstart',
		'dragging',
		'dragend',
		'addtilelayer',
		'removetilelayer',
		'load',
		'resize',
		'hotspotclick',
		'hotspotover',
		'hotspotout',
		'tilesloaded',
		'touchstart',
		'touchmove',
		'touchend',
		'longpress'
	],
	'bm-overview-map': ['viewchanged', 'viewchanging'],
	'bm-context-menu': ['open', 'close'],
	'bm-overlay': [
		'click',
		'dblclick',
		'dragend',
		'dragging',
		'dragstart',
		'mousedown',
		'mouseout',
		'mouseover',
		'mouseup',
		'addcontextmenu',
		'removecontextmenu'
	],
	'bm-marker': [
		'click',
		'dblclick',
		'mousedown',
		'mouseup',
		'mouseout',
		'mouseover',
		'remove',
		'infowindowclose',
		'infowindowopen',
		'dragstart',
		'dragging',
		'dragend',
		'rightclick'
	],
	'bm-label': ['click', 'dblclick', 'mousedown', 'mouseup', 'mouseout', 'mouseover', 'remove', 'rightclick'],
	'bm-info-window': ['close', 'open', 'maximize', 'restore', 'clickclose'],
	'bm-polyline': ['click', 'dblclick', 'mousedown', 'mouseup', 'mouseout', 'mouseover', 'remove', 'lineupdate'],
	'bm-polygon': ['click', 'dblclick', 'mousedown', 'mouseup', 'mouseout', 'mouseover', 'remove', 'lineupdate'],
	'bm-circle': ['click', 'dblclick', 'mousedown', 'mouseup', 'mouseout', 'mouseover', 'remove', 'lineupdate'],
	'bm-curve-line': ['click', 'dblclick', 'mousedown', 'mouseup', 'mouseout', 'mouseover', 'remove', 'lineupdate'],
	'bm-lushu': ['start', 'stop', 'pause'],
	'bm-rectangle-zoom': ['open', 'close'],
	'bm-info-box': ['open', 'close'],
	'bm-rich-marker': [
		'click',
		'dblclick',
		'mousedown',
		'mouseup',
		'mouseout',
		'mouseover',
		'remove',
		'infowindowclose',
		'infowindowopen',
		'dragstart',
		'dragging',
		'dragend',
		'rightclick'
	]
}
